---
- hosts: all
  become: yes
  become_user: root

  tasks:
  - name: build kernel if needed
    include_role:
      name: build_kernel
    when: buildKernel and (groups['all']|first == inventory_hostname)

  - name: enable rdma 
    include_role:
      name: rdma
    vars:
      rdma_interface: '{{ private_interface }}'
 

