---
- hosts: all
  become: yes
  become_user: root

  tasks:
#  - apt:
#      name: [ fakeroot, kernel-package, linux-source, flex, bison, libncurses-dev, flex, bison, openssl, libssl-dev, dkms, libelf-dev, libudev-dev, libpci-dev, libiberty-dev, autoconf ]
#
##   18  tar -xvf /usr/src/linux-source-5.3.0.tar.bz2
##   19  cd linux-source-5.3.0/
##   22  make oldconfig
##   33  make menuconfig
##   46  fakeroot make-kpkg clean
##   47  fakeroot make-kpkg --initrd --revision=1.0.rdma kernel_image

  - name: install rdma kernel
    apt:
      deb=/vagrant/linux-image-5.3.13_1.0.rdma_amd64.deb

  - name: Check if a reboot is required
    register: file
    stat: path=/var/run/reboot-required get_md5=no
  
  - set_fact:
     ssh_port: "{{ ssh_port|default(22) }}"
     ssh_host: "{{ ssh_host|default(inventory_hostname) }}"
  
  - name: Reboot the server
    #shell: sleep 2 && /sbin/reboot
    shell: /sbin/reboot
    poll: 0
    #async: 1
    #iignore_errors: true
    #failed_when: false
    register: reboot_out
    when: file.stat.exists == true

  - debug: var=reboot_out
  
  - name: Wait for SSH to come up
    wait_for:
      host: "{{ ssh_host }}"
      port: "{{ ssh_port }}"
      delay: 5
      timeout: 500
      state: started
    delegate_to: localhost
    become: no
    when: file.stat.exists == true
  
  - pause:
       minutes: 1
    when: file.stat.exists == true

  - apt:
      name: [ rdma-core, ibverbs-utils ]

